// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_SECURE_API_KEY',
    appId: '1:765733876116:web:453205f189d6d223a69f81',
    messagingSenderId: '765733876116',
    projectId: 'jetsetgo-c5d8c',
    authDomain: 'jetsetgo-c5d8c.firebaseapp.com',
    storageBucket: 'jetsetgo-c5d8c.firebasestorage.app',
    measurementId: 'G-GNQN4RJG8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_SECURE_API_KEY',
    appId: '1:765733876116:android:b26f3d85e72b97a3a69f81',
    messagingSenderId: '765733876116',
    projectId: 'jetsetgo-c5d8c',
    storageBucket: 'jetsetgo-c5d8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtwk_6R6Yq5euMLXrYEXbnkuAjRz8MK7k',
    appId: '1:765733876116:ios:bc9807f2a02b53f3a69f81',
    messagingSenderId: '765733876116',
    projectId: 'jetsetgo-c5d8c',
    storageBucket: 'jetsetgo-c5d8c.firebasestorage.app',
    iosBundleId: 'com.example.jetsetgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtwk_6R6Yq5euMLXrYEXbnkuAjRz8MK7k',
    appId: '1:765733876116:ios:bc9807f2a02b53f3a69f81',
    messagingSenderId: '765733876116',
    projectId: 'jetsetgo-c5d8c',
    storageBucket: 'jetsetgo-c5d8c.firebasestorage.app',
    iosBundleId: 'com.example.jetsetgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Jsjng-iajyBcYKpVzpcTyOdJMBsDxKI',
    appId: '1:765733876116:web:d8595aca845ff79aa69f81',
    messagingSenderId: '765733876116',
    projectId: 'jetsetgo-c5d8c',
    authDomain: 'jetsetgo-c5d8c.firebaseapp.com',
    storageBucket: 'jetsetgo-c5d8c.firebasestorage.app',
    measurementId: 'G-XSTDYMJR1V',
  );
}
